package com.mycompany.peluqueria;

import javax.swing.JOptionPane;

public class Peluqueria extends javax.swing.JFrame {
    Ana obj1 = new Ana();
    Ana obj2 = new Ana();
    Ana obj3 = new Ana();
    Ana obj4 = new Ana();
    Jose obj5 = new Jose();
    Jose obj6 = new Jose();
    Jose obj7 = new Jose();
    Jose obj8 = new Jose();
    Roberto obj9 = new Roberto();
    Roberto obj10 = new Roberto();
    Roberto obj11 = new Roberto();
    Roberto obj12 = new Roberto();
    Lucrecia obj13 = new Lucrecia();
    Lucrecia obj14 = new Lucrecia();
    Lucrecia obj15 = new Lucrecia();
    Lucrecia obj16 = new Lucrecia();
    /**
     * Creates new form Peluqueria
     */
    public Peluqueria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        inicioBoton = new javax.swing.JButton();
        anaBoton = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        joseBoton = new javax.swing.JButton();
        lucreciaBoton = new javax.swing.JButton();
        salirBoton = new javax.swing.JButton();
        robertoBoton = new javax.swing.JButton();
        totalesBoton = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel91 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setText("Peluqueros");

        jLabel2.setText("Ana");

        jLabel3.setText("Corte caballero :");

        jLabel4.setText("Peinado :");

        jLabel5.setText("Total recaudado :");

        jLabel6.setText("Total servicios :");

        jLabel7.setText("0");

        jLabel8.setText("Corte dama :");

        jLabel9.setText("Tintura cabello :");

        jLabel10.setText("0");

        jLabel11.setText("0");

        jLabel12.setText("0");

        jLabel13.setText("0");

        jLabel14.setText("$");

        jLabel15.setText("$");

        jLabel16.setText("$");

        jLabel17.setText("$");

        jLabel19.setText("0");

        jLabel20.setText("$");

        jLabel21.setText("0");

        jLabel22.setText("0");

        jLabel23.setText("0");

        jLabel24.setText("0");

        inicioBoton.setText("Iniciar día");
        inicioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioBotonActionPerformed(evt);
            }
        });

        anaBoton.setText("Registrar Ana");
        anaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anaBotonActionPerformed(evt);
            }
        });

        jLabel25.setText("$");

        jLabel26.setText("0");

        jLabel27.setText("0");

        jLabel28.setText("0");

        jLabel29.setText("0");

        jLabel18.setText("Corte dama :");

        jLabel30.setText("Tintura cabello :");

        jLabel31.setText("0");

        jLabel32.setText("0");

        jLabel33.setText("0");

        jLabel34.setText("0");

        jLabel35.setText("$");

        jLabel36.setText("$");

        jLabel37.setText("$");

        jLabel38.setText("$");

        jLabel39.setText("José");

        jLabel40.setText("Corte caballero :");

        jLabel41.setText("Peinado :");

        jLabel42.setText("Total recaudado :");

        jLabel43.setText("Total servicios :");

        jLabel44.setText("0");

        jLabel45.setText("0");

        joseBoton.setText("Registrar José");
        joseBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joseBotonActionPerformed(evt);
            }
        });

        lucreciaBoton.setText("Registrar Lucrecia");
        lucreciaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lucreciaBotonActionPerformed(evt);
            }
        });

        salirBoton.setText("Salir");
        salirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBotonActionPerformed(evt);
            }
        });

        robertoBoton.setText("Registrar Roberto");
        robertoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                robertoBotonActionPerformed(evt);
            }
        });

        totalesBoton.setText("Ver totales");
        totalesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalesBotonActionPerformed(evt);
            }
        });

        jLabel46.setText("Corte dama :");

        jLabel47.setText("Tintura cabello :");

        jLabel48.setText("0");

        jLabel49.setText("0");

        jLabel50.setText("0");

        jLabel51.setText("0");

        jLabel52.setText("$");

        jLabel53.setText("$");

        jLabel54.setText("$");

        jLabel55.setText("$");

        jLabel56.setText("Roberto");

        jLabel57.setText("Corte caballero :");

        jLabel58.setText("Peinado :");

        jLabel59.setText("Total recaudado :");

        jLabel60.setText("Total servicios :");

        jLabel61.setText("0");

        jLabel62.setText("0");

        jLabel63.setText("$");

        jLabel64.setText("0");

        jLabel65.setText("0");

        jLabel66.setText("0");

        jLabel67.setText("0");

        jLabel68.setText("Corte dama :");

        jLabel69.setText("Tintura cabello :");

        jLabel70.setText("0");

        jLabel71.setText("0");

        jLabel72.setText("0");

        jLabel73.setText("0");

        jLabel74.setText("$");

        jLabel75.setText("$");

        jLabel76.setText("$");

        jLabel77.setText("$");

        jLabel78.setText("Lucrecia");

        jLabel79.setText("Corte caballero :");

        jLabel80.setText("Peinado :");

        jLabel81.setText("Total recaudado :");

        jLabel82.setText("Total servicios :");

        jLabel83.setText("0");

        jLabel84.setText("0");

        jLabel85.setText("$");

        jLabel86.setText("0");

        jLabel87.setText("0");

        jLabel88.setText("0");

        jLabel89.setText("0");

        jLabel92.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Peluqueria\\img\\i3.png")); // NOI18N
        jLabel92.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel91.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel91.setText("Peluqueria UCundinamarca");

        jLabel93.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Peluqueria\\img\\i2.jpg")); // NOI18N
        jLabel93.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel94.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Peluqueria\\img\\i1.jpg")); // NOI18N
        jLabel94.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(388, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel91)
                        .addGap(121, 121, 121)
                        .addComponent(jLabel93)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel94)
                        .addGap(406, 406, 406))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel91))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel94)
                .addGap(122, 122, 122))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel92)
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel21))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42)
                            .addComponent(jLabel43)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)
                            .addComponent(jLabel44))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38)
                            .addComponent(jLabel45)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel26))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(inicioBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(anaBoton)
                                .addGap(12, 12, 12)
                                .addComponent(joseBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(robertoBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lucreciaBoton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jLabel90)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalesBoton)
                        .addGap(33, 33, 33)
                        .addComponent(salirBoton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(jLabel56)
                            .addComponent(jLabel58)
                            .addComponent(jLabel59)
                            .addComponent(jLabel60)
                            .addComponent(jLabel46)
                            .addComponent(jLabel57))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel48)
                            .addComponent(jLabel49)
                            .addComponent(jLabel50)
                            .addComponent(jLabel51)
                            .addComponent(jLabel52)
                            .addComponent(jLabel61))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel53)
                            .addComponent(jLabel54)
                            .addComponent(jLabel55)
                            .addComponent(jLabel62)
                            .addComponent(jLabel63))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel65)
                            .addComponent(jLabel66)
                            .addComponent(jLabel67)
                            .addComponent(jLabel64))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel69)
                            .addComponent(jLabel78)
                            .addComponent(jLabel79)
                            .addComponent(jLabel80)
                            .addComponent(jLabel81)
                            .addComponent(jLabel82)
                            .addComponent(jLabel68))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel70)
                            .addComponent(jLabel71)
                            .addComponent(jLabel72)
                            .addComponent(jLabel73)
                            .addComponent(jLabel74)
                            .addComponent(jLabel83))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel75)
                            .addComponent(jLabel76)
                            .addComponent(jLabel77)
                            .addComponent(jLabel84)
                            .addComponent(jLabel85))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel87)
                            .addComponent(jLabel88)
                            .addComponent(jLabel89)
                            .addComponent(jLabel86))
                        .addGap(102, 102, 102)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel39)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel44)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel31)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel32)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel33))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel26)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel27)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel28)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel29)
                                                        .addGap(30, 30, 30)
                                                        .addComponent(jLabel45))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel25)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel36)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel37)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel38)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel40)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel18)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel30)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel41)
                                                    .addGap(8, 8, 8)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel43)
                                                        .addComponent(jLabel34))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel42)
                                                        .addComponent(jLabel35))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel12))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel21)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel22)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel23)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel24)
                                                        .addGap(30, 30, 30)
                                                        .addComponent(jLabel19))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel20)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel15)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel16)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel17)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel8)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel9)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel4)
                                                    .addGap(9, 9, 9)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel13))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel14)))))))
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel92)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel90)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel61)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel48)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel50))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel64)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel65)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel66)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel67)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel62))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel63)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel53)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel54)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel55)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel57)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel46)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel47)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel58)
                                    .addGap(8, 8, 8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel60)
                                        .addComponent(jLabel51))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel59)
                                        .addComponent(jLabel52))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel78)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel83)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel70)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel71)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel86)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel87)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel88)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel89)
                                    .addGap(30, 30, 30)
                                    .addComponent(jLabel84))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel85)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel75)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel76)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel77)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel79)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel68)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel69)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel80)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel82)
                            .addComponent(jLabel73))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel81)
                            .addComponent(jLabel74))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inicioBoton)
                    .addComponent(anaBoton)
                    .addComponent(joseBoton)
                    .addComponent(lucreciaBoton)
                    .addComponent(robertoBoton)
                    .addComponent(totalesBoton)
                    .addComponent(salirBoton))
                .addGap(37, 37, 37))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioBotonActionPerformed
        jLabel7.setText("0");
        jLabel10.setText("0");
        jLabel11.setText("0");
        jLabel12.setText("0");
        jLabel13.setText("0");
        jLabel19.setText("0");
        jLabel21.setText("0");
        jLabel22.setText("0");
        jLabel23.setText("0");
        jLabel24.setText("0");
        jLabel26.setText("0");
        jLabel27.setText("0");
        jLabel28.setText("0");
        jLabel29.setText("0");
        jLabel31.setText("0");
        jLabel32.setText("0");
        jLabel33.setText("0");
        jLabel34.setText("0");
        jLabel44.setText("0");
        jLabel45.setText("0");
        jLabel48.setText("0");
        jLabel49.setText("0");
        jLabel50.setText("0");
        jLabel51.setText("0");
        jLabel61.setText("0");
        jLabel62.setText("0");
        jLabel64.setText("0");
        jLabel65.setText("0");
        jLabel66.setText("0");
        jLabel67.setText("0");
        jLabel70.setText("0");
        jLabel71.setText("0");
        jLabel72.setText("0");
        jLabel73.setText("0");
        jLabel83.setText("0");
        jLabel84.setText("0");
        jLabel86.setText("0");
        jLabel87.setText("0");
        jLabel88.setText("0");
        jLabel89.setText("0");
        obj1.resultado = 0;
        obj2.resultado = 0;
        obj3.resultado = 0;
        obj4.resultado = 0;
        obj5.resultado = 0;
        obj6.resultado = 0;
        obj7.resultado = 0;
        obj8.resultado = 0;
        obj9.resultado = 0;
        obj10.resultado = 0;
        obj11.resultado = 0;
        obj12.resultado = 0;
        obj13.resultado = 0;
        obj14.resultado = 0;
        obj15.resultado = 0;
        obj16.resultado = 0;
        obj1.numTrabajo = 0;
        obj2.numTrabajo = 0;
        obj3.numTrabajo = 0;
        obj4.numTrabajo = 0;
        obj5.numTrabajo = 0;
        obj6.numTrabajo = 0;
        obj7.numTrabajo = 0;
        obj8.numTrabajo = 0;
        obj9.numTrabajo = 0;
        obj10.numTrabajo = 0;
        obj11.numTrabajo = 0;
        obj12.numTrabajo = 0;
        obj13.numTrabajo = 0;
        obj14.numTrabajo = 0;
        obj15.numTrabajo = 0;
        obj16.numTrabajo = 0;
    }//GEN-LAST:event_inicioBotonActionPerformed

    private void anaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anaBotonActionPerformed
        String [] arreglo = {"Corte caballero","Corte dama","Tintura","Peinado"};
        double opcion = JOptionPane.showOptionDialog(rootPane, "Registrar Ana", "Elige una opción", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo,null);
        
        if (opcion == 0) {
            obj1.corteCaballero(opcion);
            jLabel21.setText(String.valueOf(obj1.resultado));
            jLabel7.setText(String.valueOf(obj1.numTrabajo));
        }
        if (opcion == 1) {
            obj2.corteDama(opcion);
            jLabel22.setText(String.valueOf(obj2.resultado));
            jLabel10.setText(String.valueOf(obj2.numTrabajo));
        }
        if (opcion == 2) {
            obj3.tintura(opcion);
            jLabel23.setText(String.valueOf(obj3.resultado));
            jLabel11.setText(String.valueOf(obj3.numTrabajo));
        }
        if (opcion == 3) {
            obj4.peinado(opcion);
            jLabel24.setText(String.valueOf(obj4.resultado));
            jLabel12.setText(String.valueOf(obj4.numTrabajo));
        }
        jLabel13.setText(String.valueOf(obj1.numTrabajo+obj2.numTrabajo+obj3.numTrabajo+obj4.numTrabajo));
        jLabel19.setText(String.valueOf(obj1.resultado+obj2.resultado+obj3.resultado+obj4.resultado));
    }//GEN-LAST:event_anaBotonActionPerformed

    private void lucreciaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lucreciaBotonActionPerformed
        String [] arreglo = {"Corte caballero","Corte dama","Tintura","Peinado"};
        double opcion = JOptionPane.showOptionDialog(rootPane, "Registrar Ana", "Elige una opción", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo,null);
        
        if (opcion == 0) {
            obj13.corteCaballero(opcion);
            jLabel86.setText(String.valueOf(obj13.resultado));
            jLabel83.setText(String.valueOf(obj13.numTrabajo));
        }
        if (opcion == 1) {
            obj14.corteDama(opcion);
            jLabel87.setText(String.valueOf(obj14.resultado));
            jLabel70.setText(String.valueOf(obj14.numTrabajo));
        }
        if (opcion == 2) {
            obj15.tintura(opcion);
            jLabel88.setText(String.valueOf(obj15.resultado));
            jLabel71.setText(String.valueOf(obj15.numTrabajo));
        }
        if (opcion == 3) {
            obj16.peinado(opcion);
            jLabel89.setText(String.valueOf(obj16.resultado));
            jLabel72.setText(String.valueOf(obj16.numTrabajo));
        }
        jLabel73.setText(String.valueOf(obj13.numTrabajo+obj14.numTrabajo+obj15.numTrabajo+obj16.numTrabajo));
        jLabel84.setText(String.valueOf(obj13.resultado+obj14.resultado+obj15.resultado+obj16.resultado));
    }//GEN-LAST:event_lucreciaBotonActionPerformed

    private void joseBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joseBotonActionPerformed
        String [] arreglo = {"Corte caballero","Corte dama","Tintura","Peinado"};
        double opcion = JOptionPane.showOptionDialog(rootPane, "Registrar José", "Elige una opción", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo,null);
        
        if (opcion == 0) {
            obj5.corteCaballero(opcion);
            jLabel26.setText(String.valueOf(obj5.resultado));
            jLabel44.setText(String.valueOf(obj5.numTrabajo));
        }
        if (opcion == 1) {
            obj6.corteDama(opcion);
            jLabel27.setText(String.valueOf(obj6.resultado));
            jLabel31.setText(String.valueOf(obj6.numTrabajo));
        }
        if (opcion == 2) {
            obj7.tintura(opcion);
            jLabel28.setText(String.valueOf(obj7.resultado));
            jLabel32.setText(String.valueOf(obj7.numTrabajo));
        }
        if (opcion == 3) {
            obj8.peinado(opcion);
            jLabel29.setText(String.valueOf(obj8.resultado));
            jLabel33.setText(String.valueOf(obj8.numTrabajo));
        }
        jLabel34.setText(String.valueOf(obj5.numTrabajo+obj6.numTrabajo+obj7.numTrabajo+obj8.numTrabajo));
        jLabel45.setText(String.valueOf(obj5.resultado+obj6.resultado+obj7.resultado+obj8.resultado));
    }//GEN-LAST:event_joseBotonActionPerformed

    private void robertoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_robertoBotonActionPerformed
        String [] arreglo = {"Corte caballero","Corte dama","Tintura","Peinado"};
        double opcion = JOptionPane.showOptionDialog(rootPane, "Registrar José", "Elige una opción", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo,null);
        
        if (opcion == 0) {
            obj9.corteCaballero(opcion);
            jLabel64.setText(String.valueOf(obj9.resultado));
            jLabel61.setText(String.valueOf(obj9.numTrabajo));
        }
        if (opcion == 1) {
            obj10.corteDama(opcion);
            jLabel65.setText(String.valueOf(obj10.resultado));
            jLabel48.setText(String.valueOf(obj10.numTrabajo));
        }
        if (opcion == 2) {
            obj11.tintura(opcion);
            jLabel66.setText(String.valueOf(obj11.resultado));
            jLabel49.setText(String.valueOf(obj11.numTrabajo));
        }
        if (opcion == 3) {
            obj12.peinado(opcion);
            jLabel67.setText(String.valueOf(obj12.resultado));
            jLabel50.setText(String.valueOf(obj12.numTrabajo));
        }
        jLabel51.setText(String.valueOf(obj9.numTrabajo+obj10.numTrabajo+obj11.numTrabajo+obj12.numTrabajo));
        jLabel62.setText(String.valueOf(obj9.resultado+obj10.resultado+obj11.resultado+obj12.resultado));
    }//GEN-LAST:event_robertoBotonActionPerformed

    private void salirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBotonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_salirBotonActionPerformed

    private void totalesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalesBotonActionPerformed
        double sumaT = (double) (obj1.resultado+obj2.resultado+obj3.resultado+obj4.resultado+obj5.resultado+obj6.resultado+obj7.resultado+obj8.resultado+obj9.resultado+obj10.resultado+obj11.resultado+obj12.resultado+obj13.resultado+obj14.resultado+obj15.resultado+obj16.resultado);
        JOptionPane.showMessageDialog(this, "Total recaudado por los peluqueros "+sumaT);
        int sumaTotalesS = (int) (obj1.numTrabajo+obj2.numTrabajo+obj3.numTrabajo+obj4.numTrabajo+obj5.numTrabajo+obj6.numTrabajo+obj7.numTrabajo+obj8.numTrabajo+obj9.numTrabajo+obj10.numTrabajo+obj11.numTrabajo+obj12.numTrabajo+obj13.numTrabajo+obj14.numTrabajo+obj15.numTrabajo+obj16.numTrabajo);
        JOptionPane.showMessageDialog(this, "Total de servicios "+sumaTotalesS);
        /*jLabel13.setText(String.valueOf(obj1.numTrabajo+obj2.numTrabajo+obj3.numTrabajo+obj4.numTrabajo));
        jLabel19.setText(String.valueOf(obj1.resultado+obj2.resultado+obj3.resultado+obj4.resultado));*/
    }//GEN-LAST:event_totalesBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peluqueria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peluqueria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peluqueria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peluqueria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Peluqueria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton anaBoton;
    private javax.swing.JButton inicioBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton joseBoton;
    private javax.swing.JButton lucreciaBoton;
    private javax.swing.JButton robertoBoton;
    private javax.swing.JButton salirBoton;
    private javax.swing.JButton totalesBoton;
    // End of variables declaration//GEN-END:variables
}
